title: "UNLIMITED BANGSUWAN"
description: "Ruang pribadi tanpa batas"
url: "https://Sulbae.github.io"
markdown: kramdown

permalink: pretty

collections:
  projects:
    output: true
    permalink: /projects/:name/
  articles:
    output: true
    permalink: /articles/:name/

readme_index:
  enabled: false
