title: "UNLIMITED BANGSUWAN"
description: "Ruang Pribadi Tanpa Batas"
url: "https://Sulbae.github.io"

markdown: kramdown
permalink: pretty
timezone: Asia/Jakarta

collections:
  projects:
    output: true
    permalink: /projects/:name/
  articles:
    output: true
    permalink: /articles/:name/

defaults:
  - scope:
      path: ""
      type: projects
    values:
      layout: tabloid

  - scope:
      path: ""
      type: articles
    values:
      layout: tabloid

author:
  name: "Anggun Sulis Setyawan"
  alias: "Bang Suwan"
  role: "Entry-level Machine Learning Engineer"

readme_index:
  enabled: false

titles_from_headings:
  enabled: false
